# application-dev.yml (개발환경)
# ./gradlew bootRun 실행 (현재 기본값 dev)

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop

  # PostgreSQL 한글 정렬(Collation) 설정
  # nickname 등 한글 필드의 ORDER BY 정렬을 위해 필요
  # 최초 DB 생성시 한번만 실행
  # 기존 docker 띄워둔 상태라면 docker compose down -v 후 재가동
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:db/init/01_create_collation.sql

decorator:
  datasource:
    p6spy:
      enable-logging: true
      logging: slf4j