# ?? ?? ?? ??
appender=com.p6spy.engine.spy.appender.Slf4JLogger

# ?? ?? ? ??? ??? ??
logMessageFormat=com.babjo.deliverycommerce.global.common.logging.P6spyFormatter

# ???? 0ms ??? ??? ?? (?? ??)
executionThreshold=0

# ?? ???? ???? ?? ?? ??
excludecategories=info,debug,result,resultset


# ????
# 16:46:20.123 [http-nio-8080-exec-1] INFO  p6spy - select * from p_user where username='user1234'